# Generated by Django 5.2.17 on 2026-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postz',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Sports', 'Sports'), ('Games', 'Games'), ('Movies/shows', 'Movies/shows'), ('Music', 'Music'), ('Other', 'Other')], default='News', max_length=20),
        ),
    ]
