# Generated by Django 5.2.17 on 2026-09-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postz',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Sports', 'Sports'), ('Games', 'Games'), ('Movies-shows', 'Movies-shows'), ('Music', 'Music'), ('Other', 'Other')], default='News', max_length=20),
        ),
        migrations.AlterField(
            model_name='postz',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
